"""
Configuration validation and template generation for OptimizerLoop.

Tasks 9.1, 9.3  — Requirements 15.2, 15.3, 15.5, 15.7

The OptimizerLoop requires exactly 6 top-level sections in every configuration
file or dict:

  1. repository   — target repo URL, branch, files
  2. llm          — provider, model, API key, generation params
  3. docker       — Dockerfile path, test command, timeout
  4. database     — SQLite path
  5. metrics      — extraction patterns, scoring, success threshold
  6. search       — strategy type, max_iterations, patience

``validate_optimizer_config`` enforces this contract and raises
``ConfigValidationError`` with a human-readable message listing all missing
sections when any are absent.

``generate_template`` writes a fully-commented YAML template to disk so users
can start a new optimization run with ``optimizer init``.
"""

from __future__ import annotations

import os
import textwrap
from pathlib import Path
from typing import Any, Dict, List, Optional, Union


# ---------------------------------------------------------------------------
# Error type
# ---------------------------------------------------------------------------

class ConfigValidationError(ValueError):
    """Raised when a configuration is missing required sections or fields.

    Attributes:
        missing_sections: Names of the top-level sections that were absent.
        message: Human-readable description of the problem.
    """

    def __init__(self, missing_sections: List[str]) -> None:
        self.missing_sections = list(missing_sections)
        detail = ", ".join(f"'{s}'" for s in self.missing_sections)
        message = (
            f"Invalid OptimizerLoop configuration: "
            f"missing required section(s): {detail}. "
            "All 6 sections are required: repository, llm, docker, "
            "database, metrics, search."
        )
        super().__init__(message)


# ---------------------------------------------------------------------------
# Required sections contract
# ---------------------------------------------------------------------------

REQUIRED_SECTIONS: List[str] = [
    "repository",
    "llm",
    "docker",
    "database",
    "metrics",
    "search",
]


# ---------------------------------------------------------------------------
# Task 9.1 — validate_optimizer_config  (Requirements 15.2, 15.3, 15.5)
# ---------------------------------------------------------------------------

def validate_optimizer_config(
    config: Union[Dict[str, Any], Any],
) -> None:
    """Validate that *config* contains all 6 required OptimizerLoop sections.

    Accepts both plain dicts (loaded from YAML) and object/namespace-style
    configs where sections are attributes.

    Args:
        config: Configuration to validate.  May be a ``dict`` or any object
                that exposes sections as attributes.

    Raises:
        ConfigValidationError: When one or more required sections are missing.
            The exception's ``missing_sections`` attribute lists every absent
            section so callers can display them all at once.

    Requirements: 15.2, 15.3, 15.5

    Examples:
        >>> validate_optimizer_config({
        ...     "repository": {...}, "llm": {...}, "docker": {...},
        ...     "database": {...}, "metrics": {...}, "search": {...},
        ... })  # OK — no exception raised

        >>> validate_optimizer_config({"repository": {...}, "llm": {...}})
        ConfigValidationError: missing required section(s): 'docker', 'database', ...
    """
    missing: List[str] = []

    for section in REQUIRED_SECTIONS:
        if isinstance(config, dict):
            present = section in config and config[section] is not None
        else:
            present = (
                hasattr(config, section)
                and getattr(config, section) is not None
            )
        if not present:
            missing.append(section)

    if missing:
        raise ConfigValidationError(missing)


# ---------------------------------------------------------------------------
# Task 9.3 — generate_template  (Requirement 15.7)
# ---------------------------------------------------------------------------

_TEMPLATE_YAML = """\
# ============================================================
# OptimizerLoop configuration template
# Generated by: optimizer init --output <file>
# All 6 sections are required.  Remove this comment when done.
# ============================================================

# 1. Repository settings ─────────────────────────────────────
repository:
  url: "https://github.com/your-org/your-repo.git"
  branch: "main"
  target_files:
    - "src/your_module.py"
  # Authentication: set GITHUB_TOKEN in your environment
  auth_token: "${GITHUB_TOKEN}"

# 2. LLM parameters ──────────────────────────────────────────
llm:
  # Provider: "openai" | "anthropic" | "ollama"
  provider: "openai"
  model: "gpt-4"
  # Set OPENAI_API_KEY in your environment
  api_key: "${OPENAI_API_KEY}"
  temperature: 0.7
  max_tokens: 4096

# 3. Docker settings ─────────────────────────────────────────
docker:
  # Path to Dockerfile relative to repo root
  dockerfile: "./Dockerfile.test"
  test_command: "pytest --benchmark-only -v"
  # Timeout in seconds per test run
  timeout: 300

# 4. Database location ───────────────────────────────────────
database:
  path: "./optimizer.db"

# 5. Metric definitions ──────────────────────────────────────
metrics:
  patterns:
    # Regex must contain exactly one capture group
    execution_time: 'Mean: ([\\d.]+) seconds'
    throughput: 'Throughput: ([\\d.]+) ops\\/sec'
  weights:
    execution_time: 0.7
    throughput: 0.3
  normalization:
    execution_time: "inverse"   # lower is better
    throughput: "direct"        # higher is better
  # Minimum fractional improvement to mark run as "Successful"
  success_threshold: 0.10

# 6. Search strategy ─────────────────────────────────────────
search:
  # Strategy: "greedy" | "beam" | "random_restart"
  strategy: "greedy"
  max_iterations: 50
  patience: 10           # stop after N generations without improvement
  # beam_width: 5        # only for beam search
  # restart_interval: 20 # only for random_restart
"""


def generate_template(output: Union[str, Path]) -> Path:
    """Write a fully-commented OptimizerLoop YAML template to *output*.

    Creates parent directories as needed.  An existing file is overwritten.

    Args:
        output: File path where the template should be written.

    Returns:
        Resolved ``Path`` of the created file.

    Raises:
        OSError: If the file cannot be written.

    Requirements: 15.7

    Example:
        >>> path = generate_template("optimizer.yaml")
        >>> print(path)
        /absolute/path/to/optimizer.yaml
    """
    output_path = Path(output).resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(_TEMPLATE_YAML, encoding="utf-8")
    return output_path
