"""
LoopBench run-mode I/O harness generator.

Many real-world scripts — competitive-programming solutions, CLI tools — read
from stdin and write to stdout at module top level. LoopBench's default harness
*imports* the target file, which crashes such scripts (they call input() on
import). Run mode instead executes the target as a subprocess, feeds it stdin,
and compares stdout against expected output.

This module generates a standard pytest file that does exactly that, so the
existing Docker sandbox and scoring pipeline work unchanged. The generated file:

  * loads the program path from LOOPBENCH_PROGRAM_PATH,
  * runs `python <program>` once per I/O case, comparing normalized stdout,
  * times the cases and prints LOOPBENCH_SPEED_MS for the speed score.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Tuple


def load_io_cases(path: str) -> List[Dict[str, str]]:
    """Load and validate I/O cases from a JSON file.

    Expected format — a list of objects, each with "input" and "output"
    (both strings), plus an optional "name":

        [
          {"name": "sample", "input": "2\\nab\\nbabba\\n", "output": "NO\\nYES"},
          {"input": "1\\naba\\n", "output": "YES"}
        ]
    """
    raw = json.loads(Path(path).read_text(encoding="utf-8"))
    if not isinstance(raw, list) or not raw:
        raise ValueError("io-tests file must be a non-empty JSON list of cases")

    cases: List[Dict[str, str]] = []
    for i, item in enumerate(raw):
        if not isinstance(item, dict) or "input" not in item or "output" not in item:
            raise ValueError(
                f"io-tests case #{i} must be an object with 'input' and 'output' keys"
            )
        cases.append(
            {
                "name": str(item.get("name", f"case{i}")),
                "input": str(item["input"]),
                "output": str(item["output"]),
            }
        )
    return cases


def generate_io_test_file(cases: List[Dict[str, str]], out_path: str, *, timeout: float = 30.0) -> str:
    """Write a pytest harness that runs the target as a subprocess.

    Args:
        cases: List of {"name", "input", "output"} dicts.
        out_path: Where to write the generated test file.
        timeout: Per-run subprocess timeout (seconds).

    Returns:
        The path that was written.
    """
    # Embed cases as a JSON literal so arbitrary input/output text is safe.
    cases_json = json.dumps(cases)
    content = _TEMPLATE.format(cases_json=cases_json, timeout=repr(float(timeout)))
    Path(out_path).write_text(content, encoding="utf-8")
    return out_path


_TEMPLATE = '''"""AUTO-GENERATED by LoopBench run-mode. Do not edit by hand."""
import json
import os
import subprocess
import sys
import time

# pyrefly: ignore [missing-import]
import pytest

_PROG = os.environ.get("LOOPBENCH_PROGRAM_PATH")
_CASES = json.loads(r"""{cases_json}""")
_TIMEOUT = {timeout}


def _normalize(text):
    """Compare outputs line-by-line, ignoring trailing whitespace and blank tail lines."""
    lines = [ln.rstrip() for ln in text.replace("\\r\\n", "\\n").split("\\n")]
    while lines and lines[-1] == "":
        lines.pop()
    return "\\n".join(lines)


def _run(stdin_text):
    if _PROG is None:
        raise RuntimeError("LOOPBENCH_PROGRAM_PATH not set")
    proc = subprocess.run(
        [sys.executable, _PROG],
        input=stdin_text,
        capture_output=True,
        text=True,
        timeout=_TIMEOUT,
    )
    if proc.returncode != 0:
        raise AssertionError(
            "program exited with code %d; stderr:\\n%s" % (proc.returncode, proc.stderr[:1000])
        )
    return proc.stdout


@pytest.mark.parametrize("case", _CASES, ids=[c["name"] for c in _CASES])
def test_io_case(case):
    """Each I/O case: feed stdin, compare normalized stdout to expected."""
    out = _run(case["input"])
    assert _normalize(out) == _normalize(case["output"]), (
        "output mismatch for case %r" % case["name"]
    )


def test_speed():
    """Time the heaviest case (largest input) to isolate algorithmic cost from
    per-process startup, and emit LOOPBENCH_SPEED_MS (avg over reps)."""
    heavy = max(_CASES, key=lambda c: len(c["input"]))
    reps = 5
    start = time.perf_counter()
    for _ in range(reps):
        _run(heavy["input"])
    elapsed_ms = ((time.perf_counter() - start) / reps) * 1000.0
    print("\\nLOOPBENCH_SPEED_MS=%.4f" % elapsed_ms)
    assert elapsed_ms < 60000, "run took %.1fms — exceeds 60s limit" % elapsed_ms
'''


def resolve_io_tests_path(explicit: str | None, target_file: Path) -> Tuple[str | None, str]:
    """Determine which I/O tests file to use.

    Precedence:
      1. An explicit --io-tests path.
      2. A conventional file next to the target: <stem>.io.json or io_tests.json.

    Returns (path_or_None, reason).
    """
    if explicit:
        return explicit, "explicit --io-tests"
    candidates = [
        target_file.with_suffix(".io.json"),
        target_file.parent / "io_tests.json",
    ]
    for c in candidates:
        if c.exists():
            return str(c), f"auto-detected {c.name}"
    return None, "none found"


def maybe_build_io_harness(
    explicit_io_tests: str | None,
    target_file: Path,
    dest_dir: Path,
) -> Dict[str, Any] | None:
    """Build the run-mode harness if I/O tests are available.

    Returns a dict with ``test_path`` and ``n_cases`` when run mode is engaged,
    otherwise None (caller falls back to import-mode test detection).
    """
    io_path, reason = resolve_io_tests_path(explicit_io_tests, target_file)
    if not io_path:
        return None
    cases = load_io_cases(io_path)
    dest_dir.mkdir(parents=True, exist_ok=True)
    harness_path = dest_dir / "_loopbench_io_test.py"
    generate_io_test_file(cases, str(harness_path))
    return {"test_path": str(harness_path), "n_cases": len(cases), "reason": reason, "io_path": io_path}
